;/*FB_PKG_DELIM*/

__d("CometFeedStoryDropdownMenuLoggerContext",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.createContext({nodeID:null});l.default=u}),98);
__d("CometList_DEPRECATED.react",["BaseList.react","react","react-compiler-runtime"],(function(t,n,r,o,a,i,l){"use strict";var e=["key"],s,u=s||(s=o("react")),c={margins:{marginBottom:"x1oo3vh0",marginTop:"x1rdy4ex",$$css:!0}};function d(t){var n=o("react-compiler-runtime").c(12),a=t.children,i=t.items,l=t.label,s=t.ref,d=t.role,m=t.testid,p=t.withNegativeMargins,_;n[0]!==a||n[1]!==i?(_=typeof a=="function"?(i!=null?i:[]).map(function(t,n){if(t==null||typeof t!="object")return null;if(t.key==null)return a({item:t,key:n});var r=t.key,o=babelHelpers.objectWithoutPropertiesLoose(t,e);return a({item:o,key:t.key})}):a,n[0]=a,n[1]=i,n[2]=_):_=n[2];var f=_,g;n[3]!==l||n[4]!==d||n[5]!==m?(g={"aria-label":l,role:d,testid:m},n[3]=l,n[4]=d,n[5]=m,n[6]=g):g=n[6];var h=g,y=p&&c.margins,C;return n[7]!==h||n[8]!==f||n[9]!==s||n[10]!==y?(C=u.jsx(r("BaseList.react"),babelHelpers.extends({},h,{ref:s,xstyle:y,children:f})),n[7]=h,n[8]=f,n[9]=s,n[10]=y,n[11]=C):C=n[11],C}l.default=d}),98);
__d("CometWearableAttributionSurfaceContext",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=e.createContext,c=u(null),d=c;l.default=d}),98);
__d("XCometPageVanityNoMediasetPhotoControllerRouteBuilder",["jsRouteBuilder"],(function(t,n,r,o,a,i,l){var e=r("jsRouteBuilder")("/{vanity}/photos/{?set}/{fbid}/",Object.freeze({}),void 0),s=e;l.default=s}),98);
__d("XCometPageVanityPhotoControllerRouteBuilder",["jsRouteBuilder"],(function(t,n,r,o,a,i,l){var e=r("jsRouteBuilder")("/{vanity}/photos/{set}/{fbid}/",Object.freeze({}),void 0),s=e;l.default=s}),98);
__d("XCometPhotoControllerRouteBuilder",["jsRouteBuilder"],(function(t,n,r,o,a,i,l){var e=r("jsRouteBuilder")("/photo/",Object.freeze({vrnav:!1}),void 0),s=e;l.default=s}),98);
__d("addToSet",[],(function(t,n,r,o,a,i){"use strict";function e(e,t){if(e.has(t))return e;var n=new Set(e);return n.add(t),n}i.default=e}),66);
__d("getCometMediaURL_media.graphql",[],(function(t,n,r,o,a,i){"use strict";var e={kind:"InlineDataFragment",name:"getCometMediaURL_media"};a.exports=e}),null);
__d("getCometMediaURL",["CometRelay","XCometPageVanityNoMediasetPhotoControllerRouteBuilder","XCometPageVanityPhotoControllerRouteBuilder","XCometPhotoControllerRouteBuilder","XCometVideoControllerRouteBuilder","getCometMediaURL_media.graphql","isStringNullOrEmpty"],(function(t,n,r,o,a,i,l){"use strict";var e;function s(t,a){var i,l,s,u,c=o("CometRelay").readInlineData(e!==void 0?e:e=n("getCometMediaURL_media.graphql"),t),d=c==null?void 0:c.id,m=(c==null?void 0:c.is_playable)===!0,p=(i=c==null||(l=c.owner)==null?void 0:l.uri_token)!=null?i:c==null||(s=c.owner)==null?void 0:s.id,_=(c==null||(u=c.owner)==null?void 0:u.__typename)==="Page";return d==null?null:m?p==null?null:r("XCometVideoControllerRouteBuilder").buildURL({page_token:p,set:a,story_token:d}):_&&p!=null?r("isStringNullOrEmpty")(a)?r("XCometPageVanityNoMediasetPhotoControllerRouteBuilder").buildURL({fbid:d,vanity:p}):r("XCometPageVanityPhotoControllerRouteBuilder").buildURL({fbid:d,set:a,vanity:p}):r("XCometPhotoControllerRouteBuilder").buildURL({fbid:d,set:a})}l.default=s}),98);
__d("removeFromSet",[],(function(t,n,r,o,a,i){"use strict";function e(e,t){if(!e.has(t))return e;var n=new Set(e);return n.delete(t),n}i.default=e}),66);
__d("useCometMediaURL_media.graphql",[],(function(t,n,r,o,a,i){"use strict";var e=(function(){var e={alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null},t=[e,{alias:null,args:null,concreteType:null,kind:"LinkedField",name:"owner",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null},e,{kind:"InlineFragment",selections:[{alias:null,args:null,kind:"ScalarField",name:"uri_token",storageKey:null}],type:"Page",abstractKey:null}],storageKey:null}];return{argumentDefinitions:[],kind:"Fragment",metadata:null,name:"useCometMediaURL_media",selections:[{kind:"InlineDataFragmentSpread",name:"getCometMediaURL_media",selections:[{alias:null,args:null,kind:"ScalarField",name:"is_playable",storageKey:null},{kind:"InlineFragment",selections:t,type:"Photo",abstractKey:null},{kind:"InlineFragment",selections:t,type:"Video",abstractKey:null}],args:null,argumentDefinitions:[]}],type:"Media",abstractKey:"__isMedia"}})();a.exports=e}),null);
__d("useCometMediaURL",["CometRelay","getCometMediaURL","react-compiler-runtime","useCometMediaURL_media.graphql"],(function(t,n,r,o,a,i,l){"use strict";var e;function s(t,a){var i=o("react-compiler-runtime").c(3),l=o("CometRelay").useFragment(e!==void 0?e:e=n("useCometMediaURL_media.graphql"),t),s;return i[0]!==l||i[1]!==a?(s=r("getCometMediaURL")(l,a),i[0]=l,i[1]=a,i[2]=s):s=i[2],s}l.default=s}),98);